### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DwainZwerg**
#### What is it?
- [ ] Bugfix
- [x] Feature
- [ ] Codebase improvement

#### Description of the changes in your PR

- Added sources: GitHub and Obtanium

#### Acknowledgement
- [x] I read the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Aga-C** [comment]
Thanks, but we don't want to have GitHub links in readme.

**Comment by DwainZwerg** [comment]
And what about Obtainium?

**Comment by Aga-C** [comment]
Obtainium is just an app for getting updates, why mention it?
In readme files we only provide links to three stores: Google Play, F-Droid and IzzyOnDroid. And for F-Droid link, there's already another pull request.

**Comment by DwainZwerg** [comment]
Following this logic, you can also leave out F-Droid, IzzyOnDroid and Google Play/Aurora Store, since you can also manually search in the apps (as in Obtainium) and then download them. These badges are there to create more convenience and not to need ≈ 12 clicks to add the app.
If you manually add an app to Obtainium, you need at least 8 clicks (there are two variants) after you have found the GitHub repo: 

1. Home screen button > launch Obtainium from the home screen (if you don’t have Obtainium on the home screen, you need one more swipe) > click on tab “Add App” > click in the search bar > enter “FossifyOrg/Clock” (16 clicks) > click on the “Search” button > click on “Select 2” > click on the radio button “FossifyOrg/Clock _(github. com)_” > click on “Pick” (> if you also want to include prerelease, flip the “Include prerelease” switch) > click on “Add”

2. Long press on the address bar in the browser > copy > home screen button > start Obtainium from the home screen (if you don’t have Obtainium on the home screen, you need one more swipe) > click on tab “Add app” > long press in the input line > click “Paste” (> flip the “Include prerelease” switch if you want prerelease) > click “Add”

**Comment by naveensingh** [comment]
Point made but I'm still not convinced. I don't want to add 'support' for every distribution channel out there.

**Comment by DwainZwerg** [comment]
> I don't want to add 'support' for every distribution channel out there.

I can fully understand that, and I wouldn't want to either. However, considering the popularity of Obtainium, I think it would be worth thinking. Finally, izzyondroid is also being added (which I think is completely unnecessary, or the reason is still unclear to me), although it's just another (due to reproducible builds probably not even faster) F-Droid repo.

**Comment by Aga-C** [comment]
The real difference is that Google Play, IzzyOnDroid and F-Droid are package repositories. They host the application on their servers. Obtainium is just a frontend to fetch updates from any repository.

And the reason, why IzzyOnDroid has been added, is that its maintainer helped us find security flaws inherited from Simple Mobile Tools and also tracks few other problems regularly, so it's a form of our gratitude to promote IzzyOnDroid.

**Pull request closed without merging**
